name: my_checkout
on:
  push:
    branches:
      - master

jobs:
  my_checkout_job:
    name: My Checkout Job
    runs-on: ubuntu-latest
    steps:
      - name: Printing a greeting
        env:
          My_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
    services:
      nginx: 
        image: nginx
        ports:
          - 8080:80

